### ISSUE TITLE
Meaning of numsites

### ISSUE THREAD

**Issue by coyotree** [blackrim/treePL#42]
Hello,

I had an interesting discussion today regarding the meaning of 'numsites' in the configuration file.

1) Does it mean the total length of the alignment used to generate the phylogeny?

OR

2) Does it mean the number of distinct alignment patterns used to build the tree (i.e. from RAxML)?

Thanks,
Cody Coyotee

**Comment by Yujiaxin419** [comment]
Hello, 

since the example file, I guess 1 is right. But I am not sure. 
I am so curious to this problem. would u please tell me how u think about it?

By the way, the word 'iterations' makes me puzzle 
(i.e. cviter = number [the number of cross validation total optimization <cmd -i>iterations<cmd -i>, default = 2]). 

would u please do me a favor to tell me anything about it ?
Thank u very much.

**Comment by Yujiaxin419** [comment]
Hello,

since the example file, I guess 1 is right. But I am not sure.
I am so curious to this problem. would u please tell me how u think about it?

By the way, the word 'iterations' makes me puzzle
(i.e. cviter = number [the number of cross validation total optimization iterations, default = 2]).

would u please do me a favor to tell me anything about it ?
Thank u very much.

**Comment by josephwb** [comment]
@coyotree it is definitely 1. The input data (i.e., edge lengths) are in units of average number of substitutions _per site_, and are estimated from all the sites (not just unique site patterns). In order to smooth the rates of substitutions per time, these edge lengths need to be first converted into numbers of actual substitutions.
